config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'
  get "/help", to: "home#help"
  get "/home/crawl", to: "home#crawl"
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources  :users,    only: :show
  resources  :products, only: [:create, :show, :update, :destroy]
  post "/update_all_products", to: "products#update_all"

  # action cable
  mount ActionCable.server => '/cable'

  # sidekiq dashboard
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def help
  end

  def crawl
    if params[:product_url].present? && params[:site][:name].present?
      crawler = Crawler::CrawlerService.new(product_url: params[:product_url], site_type: params[:site][:name])
      @crawl_result = crawler.crawl
      respond_to do |format|
        format.html { redirect_to root_url }
        format.js
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_crawl_result.html.erb
<% if @crawl_result.present? %>
  <div class="result">
    <div class="product">
      <h3><%= @crawl_result[:name] %></h4>
      <h4><%= @crawl_result[:display_price] %></h4>
      <%= image_tag @crawl_result[:image_url], class: "product-image" %>
    </div>
    <%= link_to "商品をリストに登録する", products_path(name:          @crawl_result[:name],
                                                    base_price:    @crawl_result[:current_price],
                                                    current_price: @crawl_result[:current_price],
                                                    display_price: @crawl_result[:display_price],
                                                    image_url:     @crawl_result[:image_url],
                                                    product_url:   params[:product_url],
                                                    site_type:     params[:site][:name]
                                                    ), method: :post, class: "btn btn-success" %>
  </div>
<% end %>

app/views/home/crawl.js.erb
$('#crawl_result').replaceWith('<div id="crawl_result"><%= j(render "crawl_result") %></div>');

app/views/home/help.html.erb
<div class="page-title">
  <h1 class="center">使い方</h1>
</div>
<div class="container-white">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2>PriceManagerは気になる商品の価格ウォッチリスト作成サービスです</h2>
      <h3>あなたのお買い物に是非お役立てください</h3>
      <p>※現在対応サイト：Amazon、Wiggle(スポーツ用品通販)、BellatiSport(ロードバイク通販)</p>
      <p>(その他のサイトも順次対応予定)</p>
    <!-- タブ・メニュー -->
      <ul class="nav nav-tabs">
        <li class="nav-item active"><a href="#how_to_use" data-toggle="tab" class="nav-link">商品の登録</a></li>
        <li class="nav-item"><a href="#update_price" data-toggle="tab" class="nav-link">価格の更新</a></li>
        <li class="nav-item"><a href="#notes" data-toggle="tab" class="nav-link">利用上の注意</a></li>
      </ul>

      <!-- タブ内容 -->
      <div class="tab-content">
        <div class="tab-pane active" id="how_to_use">
          <div id="how_to_use_1">
            <p>※Amazonの商品での例</p>
            <h3>1.商品ページのURLをコピーする</h3>
            <%= image_tag "amazon.png", alt: "how_to_use_for_amazon" %>
          </div>
          <div id="how_to_use_2_3_4">
            <h3>2.フォームにURLを貼り付ける</h3>
            <h3>3.商品サイトを選択</h3>
            <h3>4.ボタンをクリック</h3>
            <%= image_tag "fill_in_forms.png", alt: "fill_in_forms" %>
          </div>
          <div id="how_to_use_5">
            <h3>5.商品情報が表示されるので、ボタンをクリックしてリストに追加</h3>
            <%= image_tag "result.png", alt: "result" %>
          </div>
          <div id="how_to_use_6">
            <h3>6.商品情報がリストに追加される</h3>
            <%= image_tag "product_page.png", alt: "product_page" %>
          </div>
        </div>
        <div class="tab-pane fade" id="update_price">
          <div id="update_1">
            <h3>1.ボタンをクリックすると商品価格を更新します</h3>
            <%= image_tag "before_update.png", alt: "before_update" %>
          </div>
          <div id="update_2_3">
            <h3>2.商品情報の取得に成功すると、価格が更新されます</h3>
            <h3>3.登録時の価格から変動していれば、その価格差が表示</h3>
            <%= image_tag "after_update.png", alt: "after_update" %>
          </div>

        </div>
        <div class="tab-pane fade" id="notes">
          <h2>※注意事項</h2>
          <div class="note">
            <p>・「すべての商品価格を更新する」により、登録した全商品の価格を一度に更新できます。</p>
            <p>ただし、商品数が多い場合、この処理は非常に時間がかかり、商品サイトへの負荷がかかることも考えられます。</p>
            <p>できる限り、価格を更新したい商品ページから個別に更新するようお願いいたします。</p>
          </div>
          <div class="note">
            <p>・商品サイトへの負荷を避けるために、同じ商品の価格を連続で更新することはお控えください。</p>
          </div>
          <div class="note">
            <p>・商品サイトの構成が変わると、商品情報が正確に取得できない場合がございます。</p>
            <p>こうした不具合については確認次第対応いたします。</p>
          </div>
          <div class="note">
            <p>・実際の商品サイトと、ドロップダウンリストから選択したサイトが一致しない場合、商品情報が取得できませんのでご注意ください。</p>
          </div>
          <div class="note">
            <p>・AmazonのKindle本については未対応になります。</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container-white">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="top-wrapper">
        <div id="site_logo_area">
          <%= image_tag "site_logo.png", alt: "Price Manager" %>
        </div>
        <%= link_to help_path, id: "link_to_help_page" do %>
          <h4>※初めての方はこちらから使い方をお読みください</h3>
        <% end %>
        <div id="product_url_form">
          <%= form_tag(home_crawl_path, method: :get, remote: true) do %>
            <div class="url-form">
              <p>商品ページのURLを入力</p>
              <%= text_field_tag(:product_url, nil, placeholder: "URLを入力") %>
            </div>
            <div class="site-list">
              <p>商品サイトを選択</p>
              <%= select :site, :name, [["Amazon(本除く)", :amazon], ["Amazon本(Kindle本除く)", :amazon_book], ["Wiggle", :wiggle], ["Bellati Sport", :bellati]], prompt: "サイトを選択" %>
            </div>
            <input type="submit" value="商品情報を取得する" class="btn btn-success" data-behavior=crawl_btn>
          <% end %>
        </div>

        <div id="crawl_result">
        </div>
      </div>
    </div>
  </div>
</div>