config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'
  get "/help", to: "home#help"
  get "/home/crawl", to: "home#crawl"
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources  :users,    only: :show
  resources  :products, only: [:create, :show, :update, :destroy]
  post "/update_all_products", to: "products#update_all"

  # action cable
  mount ActionCable.server => '/cable'

  # sidekiq dashboard
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "HOME", root_path, class: "navbar-brand" %>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "使い方", help_path %></li>
      <% if user_signed_in? %>
        <li>
          <%= link_to current_user.name, user_path(current_user) %>
        </li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "ユーザー登録", new_user_registration_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>    
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render "layouts/head" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="all-container">
      <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>

        <%= yield %>

        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </body>
</html>